### ISSUE TITLE
Ternary plot triangle not alligned with custom barycentric vertices

### ISSUE THREAD

**Issue by Nate-Wessel** [davenquinn/d3-ternary#9]
I'm having trouble getting the ternaryPlot object in the right coordinate space after setting custom vertices for a barycentric coordinate system. 

Working example here:
https://observablehq.com/@nate-wessel/ternary-vertices-bug

Using the barycentric object I instantiated, I am able to plot my points within the coordinate space defined for my vertices, but when I try to plot the triangle via the ternaryPlot object, it seems to give me results that are way out in left field. Shouldn't it get the custom vertices from the barycentric object and know what to do with them?

It's unclear to me what the relation is between `barycentric()` and `ternaryPlot()`. An example showing how to use custom vertices would be greatly appreciated.

**Comment by JulesBlm** [comment]
Hi Nate, heres a demo notebook showing how to use custom vertices with a ternary plot: https://observablehq.com/@julesblm/right-angle-ternary-plot?collection=@julesblm/ternary-plots

It’s late here, so I will take a closer look at your notebook tomorrow.

**Comment by Nate-Wessel** [comment]
Thanks! No hurry. 

I took a look through that right-angle example again just now, and seem to have solved my issue, though I don't yet understand why. 

I had a hunch that my problem had something to do with a radius setting since you had set that explicitly and I hadn't. I tried setting my `ternaryPlot` radius to 1, and boom - solved! I had though that would produce a really tiny triangle somewhere on my plot but that I would be able to identify it and maybe iteratively increase the size until I figured out what value it might actually correspond to. 

Curiously, I then tried setting the radius to `1.1`, expecting to see the triangle expand beyond the points defining the corners of the plot, i.e. expanding around the center of the plot - but it didn't. It seems to have translated out from the plot origin of `[0,0]` which the plot is not centered on. 

So now I have no idea what the radius setting does. But it works!

**Comment by JulesBlm** [comment]
Had to read my the docs I wrote again to remember how it works. I think I made it so that `barycentric` works in unit circle values and `ternaryPlot.radius()` takes a pixel radius (usually a few hundred px) to scale the barycentric vertices. The default radius of `ternaryPlot` is set to 300 (px), so I think your triangle was initially too large. Though it seems that passing in 'display values' to `barycentric.vertices()` and setting to ternary plot radius to 1 works just as well.

> Curiously, I then tried setting the radius to 1.1, expecting to see the triangle expand beyond the points defining the corners of the plot, i.e. expanding around the center of the plot - but it didn't. It seems to have translated out from the plot origin of [0,0] which the plot is not centered on.

Yeah, [`barycentric`](https://github.com/davenquinn/d3-ternary#barycentric) assumes it's centered at the origin and currently there's no option to change that. You'll have to manage the offset yourself. Adding or calculating a center from given vertices might be a good future addition though.

> But it works!

Excellent! Can I close this issue?

**Comment by Nate-Wessel** [comment]
Aha. Ok, I think I understand now. 

So it seems like setting vertices on `barycentric` is really about setting relative angles/positions (vertices on the unit circle), and then `ternaryPlot` is meant to handle all of the display issues and scaling. I probably shouldn't have been using `barycentric` to get the display position of my points, but rather `ternaryPlot`. That makes sense since `ternaryPlot` has all the scale, transform, etc display-type methods. 

Thanks for the explanation! And for this library in general. Very helpful!!

**Comment by JulesBlm** [comment]
Exactly right. Thank you, nice to hear that the library is helpful!
